### ISSUE TITLE
io.minio.errors.XmlParserException: null

### ISSUE THREAD

**Issue by kongmaster2016** [minio/minio-java#1007]
code:
minioClient.putObject(PutObjectArgs.builder().bucket(bucketName).object(ObjectName).stream(in,  -1, 10485760)

exception:
io.minio.errors.XmlParserException: null
	at io.minio.Xml.unmarshal(Xml.java:68)
	at io.minio.MinioClient.execute(MinioClient.java:1050)
	at io.minio.MinioClient.putObject(MinioClient.java:7582)
	at io.minio.MinioClient.putObject(MinioClient.java:4682)
	at io.minio.MinioClient.putObject(MinioClient.java:4881)

**Comment by balamurugana** [comment]
@kongmaster2016
Please provide more information and enable `traceOn()` and provide HTTP traces as well.

Moreover we have [functional tests](https://github.com/minio/minio-java/blob/release/functional/FunctionalTest.java#L823-L837) to cover the case. I don't think the problem is at `minio-java` side.

**Comment by balamurugana** [comment]
@kongmaster2016 Reopen this issue with necessary detail.

**Comment by Aaronwang81** [comment]
I also encountered the same problem
I use Minio to upload files to CloudFlare R2
If I don't set the 'region' to the MinioClient and PubObjectArgs，the R2 server return a XML HTTP Body, and the MinioClient will throw io.minio.errors.XmlParserException,
For my problem, the solution is set region to 'auto'.
