### ISSUE TITLE
Exception infomation lost when some Exception occurs 

### ISSUE THREAD

**Issue by terrason** [minio/minio-java#1409]
![图片](https://user-images.githubusercontent.com/4081996/209908293-1b68afe6-3ab6-4af2-a262-2aafeaadbd53.png)
I meet an OOM Exception ,but it's hard to  find out .  The exception caught outside  just says: java.lang.RuntimeException: null
```
Caused by: java.lang.RuntimeException: null
	at io.minio.S3Base.throwEncapsulatedException(S3Base.java:243)
	at io.minio.MinioClient.putObject(MinioClient.java:1375)
        ....
```

I personally strongly advise to fix this by changing _io.minio.S3Base.java:243_ with :
```
- throw new RuntimeException(exc.getCause());
+ throw new RuntimeException("Failed to put object:" + ext.getMessage(), exc);
```
The error message may be something better.
https://github.com/minio/minio-java/blob/8c7a5be3a42ae0e1f4da9269e97a30729b3cbf83/api/src/main/java/io/minio/S3Base.java#L243

**Comment by balamurugana** [comment]
Feel free to send a PR

**Comment by minus7** [comment]
Unfortunately, only the `ExecutionException` passed into `throwEncapsulatedException` has the stack trace from the call site. The cause in it doesn't have a meaningful stack trace since it comes from a different thread. The only way to keep the stack trace would be to keep `ExecutionException`, but doing so would make pretty much all checked exception annotations on API functions invalid and make it harder to check the type of exception.

**Comment by geniusxc** [comment]
A header you provided implies functionality that is not implemented？ anyone met this problem when use the .startAfter() for querying objects

**Comment by balamurugana** [comment]
Closing as stale issue
