### ISSUE TITLE
AuthorizationHeaderMalformed: the region is wrong when using MinioClient to query local minio

### ISSUE THREAD

**Issue by simonedavico** [minio/minio-java#289]
I have setup a minio instance on my machine, running in a docker container through the [Docker minio image](https://hub.docker.com/r/minio/minio/). I tried to add and list buckets from `mc`, with no issue.

Anyway, when I try to list the buckets with a library call, I get the following error:

```
Please open an issue with this bug at http://github.com/minio/minio-java
<?xml version="1.0"?><Error xmlns="">     <Code>AuthorizationHeaderMalformed</Code>
<HostId>3L137</HostId>
<Message>The authorization header is malformed; the region is wrong; expecting 'milkyway'.</Message>
<RequestId>3L137</RequestId>
<Resource>/</Resource>
</Error>
io.minio.errors.InternalClientException
	at io.minio.MinioClient.parseError(MinioClient.java:356)
	at io.minio.MinioClient.listBuckets(MinioClient.java:820)
        ....
```

I just started playing around with minio today, so I don't know if this is a bug in the library or some error from my side (more likely). I don't see any way to set the region minio is expecting on the request header manually. 
This is the code causing the exception:

```java
...
MinioClient minioClient = new MinioClient(address, accessKey, secretKey);
minioClient.listBuckets().forEachRemaining(bucket ->  logger.debug(bucket.getName()));
...
```

**Comment by harshavardhana** [comment]
There was a recent change on minio server which changed the default region from 'milkyway' to 'us-east-1' to cater for other S3 compatible services.

You should use the 0.2.5 version of the released java library for now, since you are using the docker image for 'minio' which is still not updated with the latest master. 

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.minio%22%20AND%20a%3A%22minio%22

I will upload new binaries for minio/minio server change soon.

**Comment by simonedavico** [comment]
The above code runs fine now, thank you!

**Comment by harshavardhana** [comment]
> The above code runs fine now, thank you!

Closing the issue, feel free to open new ones if you have new issues or questions.
