### ISSUE TITLE
make putobject to support unknown sized stream

### ISSUE THREAD

**Issue by balamurugana** [minio/minio-java#341]

**Comment by FlorinAsavoaie** [comment]
Since there are no specs for this, I started with that. Going through the code, I noticed the following:
- There is a maximum size of an object. How is that supposed to be handled in the case of an unknown sized stream? Just upload parts until we reach the limit and if we reach the limit stop? If/when we stop, do we cleanup what we uploaded already or will an incomplete upload remain there?
- Should we define a fixed size of multipart uploads of unknown sized objects? I can't think of another way to do it. In fact I think this should be done for all objects. If we do this, we can completely rewrite the putObject method to never require the size of the object except that it would be able to check size constraints earlier.

**Comment by balamurugana** [comment]
@FlorinAsavoaie 

> There is a maximum size of an object. How is that supposed to be handled in the case of an unknown sized stream? Just upload parts until we reach the limit and if we reach the limit stop? If/when we stop, do we cleanup what we uploaded already or will an incomplete upload remain there?
> Should we define a fixed size of multipart uploads of unknown sized objects? I can't think of another way to do it. In fact I think this should be done for all objects. If we do this, we can completely rewrite the putObject method to never require the size of the object except that it would be able to check size constraints earlier.

* As per minio-go, for unknown sized stream, stream size is assumed to  `MAX_OBJECT_SIZE` (ie 5TiB).
* Using `MAX_OBJECT_SIZE` as size to [calculateMultipartSize()](https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/MinioClient.java#L2841) returns `{ (int) partSize, (int) partCount, (int) lastPartSize }`.
* We would need to use `partSize` and `lastPartSize`.
* In [putObject()](https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/MinioClient.java#L2134), we would need to allocate `partSize` of byte array and read from the stream upto `expectedReadSize` in the [for loop](https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/MinioClient.java#L2134).  If EOF is got, keep `bytesRead` as `expectedReadSize` and `partCount` as `partNumber`.

Once this is done, rest of the thing works transparently.  Hope this helps.

**Comment by deekoder** [comment]
Refer to how we handle this in minio-go

**Comment by balamurugana** [comment]
Requires for https://github.com/minio/minio-java/issues/536
