### ISSUE TITLE
api: Retreive set meta data. 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio-java#452]
As reported by  @tanquetav in the channel, 

> I am trying to use X-Amz-Meta- with java client. I successfully upload content to minio with this user metadata. Unfortunately, the java client do not return this headers. I think in extend MinioClient in my application to achieve this, but executeHead, execute are private. Is possible use this functions? I need to put them protected access. 

> ObjectStat exposes few items, like etag, name date. I want to expose user defined metadata too.

**Comment by harshavardhana** [comment]
@hackintoshrao moved this as won't fix.

**Comment by hackintoshrao** [comment]
@tanquetav, Minio discourages the use of `X-AMZ-Meta` since with the backend setup which is build for an object storage system its not possible to query Meta data.

**Comment by tanquetav** [comment]
@hackintoshrao In fact minio server store and retrieve these information. I will choose another java api to achieve these.

**Comment by harshavardhana** [comment]
> @hackintoshrao In fact minio server store and retrieve these information. I will choose another java api to achieve these.

We do store this but since this metadata has no way to be queried other than GetObject/HeadObject, it invites bad practice. 

Object storage APis are limited and generally not queriable - so keep these metadata on an object storage serves limited purpose IMHO. 

Keeping it in a database outside of object storage makes life easier for the application as well.
