### ISSUE TITLE
Conflicts with Reflections

### ISSUE THREAD

**Issue by MatteCarra** [minio/minio-java#544]
Minio conflicts with reflections, maybe because Minio is using an old version of google guava.
This is the exception:

> java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;
        at org.reflections.Reflections.expandSuperTypes(Reflections.java:380)
        at org.reflections.Reflections.<init>(Reflections.java:126)
        at org.reflections.Reflections.<init>(Reflections.java:168)
        at org.reflections.Reflections.<init>(Reflections.java:141)

**Comment by balamurugana** [comment]
@MatteCarra Could you give me a full stacktrace? I don't see any minio related trace in the trace you pasted

**Comment by MatteCarra** [comment]
Minio uses an outdated of guava, which causes conflicts with other dependencies, like [Reflections](https://github.com/ronmamo/reflections)

**Comment by balamurugana** [comment]
@MatteCarra gradle/maven allow each library can use its own version of dependencies.  I am unable to understand `outdated of guava and conflicts`.

Do you mean `com.google.guava:guava:18.0` is having problem in general?  Aren't you able to use different version of guava whereas minio-java uses `guava:18.0`?

**Comment by MatteCarra** [comment]
I have a project that uses Reflections and Minio.
I can't understand why, but guava 18.0 and guava 20.0 (Reflections is using this guava version) are in conflict.

**Comment by balamurugana** [comment]
This is a known problem in a project using multiple dependent packages.  You would need to resolve in your project to use such conflicting dependencies using maven/gradle.  This [stackoverflow](http://stackoverflow.com/questions/19659425/conflicting-library-version-in-a-java-maven-project) would be helpful if you are using maven.

Increasing guava dependency version in minio-java would conflict with someone who depends on different version of guava.  This is not the solution unless otherwise there is a strong reason for that.

**Comment by vivek1739** [comment]
check your $CLASSPATH once. 
It may be pointing to old gauva jars like in hadoop , hive etc.
Comment the old ones in CLASSPATH and add the confluent common and kafka jar location.
Then it will work
