### ISSUE TITLE
get jwt token

### ISSUE THREAD

**Issue by xiaochen2012** [minio/minio-java#610]
I want to download bucket files in bulk. I see the browser that can be downloaded through http://localhost:9000/minio/zip token=xxx, and whether SDK can provide get  token function

**Comment by balamurugana** [comment]
There is no single method to do it.  You could call multiple `getObject()` in parallel. `MinioClient` is thread-safe to use.

**Comment by xiaochen2012** [comment]
we are use js  call download url ,so getObject not suit, thank you 。

**Comment by nitisht** [comment]
Hi @xiaochen2012 functionality to download files with jwt token is for internal use, specific to the Minio browser. It is not recommended to build functionality on top of token as it may change without notice. It is better to follow idiomatic S3 approach.

Since S3 does not provide API for bulk download of files from a bucket, a better approach is to 

- Call multiple `PresignedGetObject()`, one of each file to download.
- Stream the `PresignedGetObject()` output into a single zip writer. 

For streaming you can refer projects like https://github.com/DanielHindi/aws-s3-zipper

**Comment by xiaochen2012** [comment]
ok，thanks
