### ISSUE TITLE
Support directory operation

### ISSUE THREAD

**Issue by cwjcsu** [minio/minio-java#653]
statObject/putObject with objectName end with '/' will fail;
when remove an object that is the only file in a directory,the containing directory will be removed too.

**Comment by balamurugana** [comment]
> statObject/putObject with objectName end with '/' will fail;

This is already fixed by https://github.com/minio/minio-java/pull/650.  Can you try and confirm with latest master?

> when remove an object that is the only file in a directory,the containing directory will be removed too.

There is no such directory concept in object storage.  All objects are stored, retrieved and deleted.  When an object ending with `/` is called as directory by users, but it is an independent object which is entirely different object where another object name prefixing with `a directory object`.  Below is an example
* Create an directory object `photos/2006/January/`.  Note that this object can also hold content as any other object.  Traditionally users create empty object to denote it as directory (like file system).
* Create another object `photos/2006/January/sample.jpg` which is completely independent.  When listing objects, users asks to view it as directory tree by delimiting the list by `/`.  Object storage provides such filtering.
* In the above case, it is user's responsibility to remove those two objects i.e. object storage does not aware whether it is a directory tree.  Note that you could remove those objects in any order (not like file system).

For your requirement, you could use http://minio.github.io/minio-java/io/minio/MinioClient.html#removeObject-java.lang.String-java.lang.Iterable- by providing list of objects to delete or do listing as per requirement using http://minio.github.io/minio-java/io/minio/MinioClient.html#listObjects-java.lang.String-java.lang.String-boolean-  and delete individually using http://minio.github.io/minio-java/io/minio/MinioClient.html#removeObject-java.lang.String-java.lang.String-

**Comment by cwjcsu** [comment]
i tested the code with latest master,the end-with '/' problem solved.Thanks.
