### ISSUE TITLE
Consecutive downloads fail.

### ISSUE THREAD

**Issue by shabtu** [minio/minio-java#678]
**Summary**
I use Elasticsearch to index files in Minio to be available for search and retrieval.
The files are guaranteed to exist in Minio since they would not exist in Elasticsearch otherwise (bucket notifications are used for this).

**Expected Behavior**

The files should be downloaded to the same directory consecutively from Minio through the getObject- function.

**Current Behavior**
When I try to download the previously uploaded/indexed files consecutively the first few (about 10) succeed and the rest if the 2000 total fail randomly.

**Steps to Reproduce**

Upload many files to Minio.
List the file names in minio-java.
Download the listed files consecutively.
Environment
Minio on Docker: RELEASE.2018-04-27T23-33-52Z
Java 8 on Windows

Link to your project:
[https://github.com/shabtu/fileservice]

**Comment by shabtu** [comment]
@deekoder There is no actual error, it is just that a few of the files are successfully downloaded and the rest are not. The files are found in the bucket but the retrievals fail after a few files. 

Could the rate that I am trying to download them in be too much to handle for the server?

**Comment by shabtu** [comment]
``API: CopyObject(bucket=retrievedfiles, object=44013796/885/2018-03-13/1486d5e5-9879-4630-82a2-752803f3299b/invoiceGenera
ted.pdf)
Time: 08:21:33 UTC 05/08/2018
RemoteHost: 172.17.0.1:60780
UserAgent: Minio (x86; x86) minio-java/dev
Error: file access denied
       1: cmd/fs-v1-helpers.go:237:cmd.fsStatFile()
       2: cmd/fs-v1.go:663:cmd.(*FSObjects).parentDirIsObject.func1()
       3: cmd/fs-v1.go:669:cmd.(*FSObjects).parentDirIsObject.func1()
       4: cmd/fs-v1.go:669:cmd.(*FSObjects).parentDirIsObject.func1()
       5: cmd/fs-v1.go:669:cmd.(*FSObjects).parentDirIsObject.func1()
       6: cmd/fs-v1.go:671:cmd.(*FSObjects).parentDirIsObject()
       7: cmd/fs-v1.go:734:cmd.(*FSObjects).putObject()
       8: cmd/fs-v1.go:417:cmd.(*FSObjects).CopyObject()
       9: cmd/object-handlers.go:539:cmd.objectAPIHandlers.CopyObjectHandler()
      10: cmd/api-router.go:75:cmd.(objectAPIHandlers).CopyObjectHandler-fm()
      11: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()``


Here is what shows in the minio server, I got the same messages when it was working so I am just assuming these are not the issue? I might very well be wrong!

**Comment by Praveenrajmani** [comment]
Hey @shabtu , 

Both aws s3 and Minio does not support `meta object puts`.
ie, if `a/b/c/d/e.txt` is an object to be put in a `bucket` , The `bucket` should not have any of the following objects

- "a/b/c/d"
- "a/b/c"
- "a/b"
- "a"

To put it simple - `The parent directory of an object should not be an object itself`

From the error stack above i infer that there is already an object `44013796` in the `retrievedfiles` bucket , So put request for `44013796/885/2018-03-13/1486d5e5-9879-4630-82a2-752803f3299b/invoiceGenera` will not be permitted since its parent is already residing under the bucket.

PS: You can use the latest version `RELEASE.2018-08-02T23-11-36Z`

**Comment by deekoder** [comment]
@shabtu  please let us know if this helped. We will close this for now. Could you reactivate it if you think we haven't addressed your concern?
