### ISSUE TITLE
Expose continuation-token for manual pagination

### ISSUE THREAD

**Issue by IsNull** [minio/minio-java#752]
Currently the Java Api returns listObjects as `Iterable<>` and hides the continuation-token logic behind it.
This is nice in some circumstances, but in others it is necessary to handle the iteration manually. Currently there is no workaround possible since the API is too opinionated about this.

Can you expose an API where the user can provide a continuation-token and return a single chunk at a time (similarly to what the official S3 SDK is doing?

```java
ListObjectsResponse listObjectsContinuable(String bucket, String nextContinuationToken);
ListObjectsResponse listObjectsContinuable(String bucket, String prefix, String nextContinuationToken);
ListObjectsResponse listObjectsContinuable(String bucket, String prefix, boolean recursive, String nextContinuationToken);
```

The `ListObjectsResponse` would consist of the chunk of items and also hold the continuation token for fetching the next chunk.

```java
public class ListObjectResponse {
   private List<Result<Item>> items;
   private String continuationToken;
   private String nextContinuationToken; 

   // Getters / Setters
}
```

Any chance you could support this?

**Comment by kannappanr** [comment]
@IsNull Currently, I don't think we expose this in any of our APIs. In general, this is done to keep things simple in our APIs. Will check internally with our team and see if it makes sense for us to add support to pass continuation token.

**Comment by IsNull** [comment]
@kannappanr Thanks for your response. As I can see from the MinioClient Source, the two required methods already exist, but are obviously private:

```java
/**
   * Returns {@link ListBucketResult} of given bucket, marker, prefix and delimiter.
   *
   * @param bucketName        Bucket name.
   * @param continuationToken Marker string.  List objects whose name is greater than `marker`.
   * @param prefix            Prefix string.  List objects whose name starts with `prefix`.
   * @param delimiter         Delimiter string.  Group objects whose name contains `delimiter`.
   */
  private ListBucketResult listObjectsV2(String bucketName, String continuationToken, String prefix, String delimiter)
```
[Source](https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/MinioClient.java#L3009)

```java
  /**
   * Returns {@link ListBucketResultV1} of given bucket, marker, prefix and delimiter.
   *
   * @param bucketName Bucket name.
   * @param marker     Marker string.  List objects whose name is greater than `marker`.
   * @param prefix     Prefix string.  List objects whose name starts with `prefix`.
   * @param delimiter  delimiter string.  Group objects whose name contains `delimiter`.
   */
  private ListBucketResultV1 listObjectsV1(String bucketName, String marker, String prefix, String delimiter)
```
[Source](https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/MinioClient.java#L3181)

If we can access those two from the outside, it would be fine.

In case you dont like to pollute the current API with the more low-level methods,  you could simply mark them `protected` so that they can be accessed by subclassing MinioClient.

**Comment by aalex21** [comment]
Currently, we are facing heap size/ out of memory issue, because of lack of availability of continuation-token.

We tried a test to list objects from S3 (approx 2200 objects meta data) with 10 concurrent requests (2200 *10).
This occupies 90%+ of 3GB heap size. The main issues found from Minio code is
1) Since continuation token is hidden and Minio loads all 2200 meta data information to memory
2) The XML parsing to form the iterator looks not optimal

Suggestion
1) Make the continuation token available outside, so that we can control batch query and control memory
2) Support to return the HTTP response directly, so that we can do some optimal parsing as per the data we need

**Comment by IsNull** [comment]
@aalex21 I suggest you look into the official s3 java clients (sdk v2) from aws. They provide a very good API experience and are well written. We use it without any issues with minio servers.

**Comment by harshavardhana** [comment]
As @kannappanr suggested @aalex21 minio-java is not meant for such use cases full control over the iterator means exposing the lower-level API, which was never our interest. 

We would definitely want to address the memory usage though, I am not sure why would they take 3GiB worth of memory which seems like a lot.

**Comment by senthillogs** [comment]
> Currently, we are facing heap size/ out of memory issue, because of lack of availability of continuation-token.
> 
> We tried a test to list objects from S3 (approx 2200 objects meta data) with 10 concurrent requests (2200 *10).
> This occupies 90%+ of 3GB heap size. The main issues found from Minio code is
> 
> 1. Since continuation token is hidden and Minio loads all 2200 meta data information to memory
> 2. The XML parsing to form the iterator looks not optimal
> 
> Suggestion
> 
> 1. Make the continuation token available outside, so that we can control batch query and control memory
> 2. Support to return the HTTP response directly, so that we can do some optimal parsing as per the data we need

We are also facing the same issue.

**Comment by balamurugana** [comment]
@aalex21 @senthillogs 
`listObjects()` APIs come with optional parameters like `prefix`, `recursive` and `useVersion1` (rarely useful option). Your listing can be controlled with these parameters.

If you are listing all objects all the time is not better way to do so. You could use specific prefix listing and/or non-recursive listing to control listing.

As logic in `private Iterable<Result<Item>> listObjectsV2(final String bucketName, final String prefix, final boolean recursive)` method is concerned, it gets XML data of batch of 1000 objects one after another. At any moment, XML parsed (maximum of) 1000 objects information is held in memory. In your 2200 objects case, the memory usage is 1000 + 1000 + 200 objects information not all 2200 objects.

In your case of 90%+ of 3GB heap used is concerned, there could be some other memory leak or you would need to trigger GC to kick in. XML data of 1000 objects + parsed 1000 objects information wouldn't take more than few MBs (I haven't measured the numbers myself, If possible you could post your memory usage information along with program you used. So that I can reproduce it here).

Solutions to this problem can be
1. Using `prefix` and/or `recursive` option.
2. Limiting `max-keys` to < 1000. Code change is required. Patches are welcome.
3. I wouldn't recommend exposing `continuation-token` instead you could use raw S3 APIs directly.

**Comment by harshavardhana** [comment]
manual pagination is not part of our design in our SDKs, our SDKs are meant to be consumed for applications which do not want them to be tied to S3 APIs and are not tied to lower-level details. If manual pagination is needed you need to write your own REST wrappers for such an operation.
