### ISSUE TITLE
checkBucketName() method doesn't consider creating multiple buckets at a time

### ISSUE THREAD

**Issue by looksworking** [minio/minio-java#760]
Inconsistent behavior with `mc mb <bucketName>`:
mc creates all buckets in given path like mkdir -p:
`$ mc mb files/ffa/7ee/ffa7ee54-8c0f-465f-bf1f-f8cd1d4179e3/`
`Bucket created successfully files/ffa/7ee/ffa7ee54-8c0f-465f-bf1f-f8cd1d4179e3/`
while Java client's method `checkBucketName` has a regex 
`name.matches("^[a-z0-9][a-z0-9\\.\\-]+[a-z0-9]$")`
which throws exception io.minio.errors.InvalidBucketNameException on 
`minioClient.makeBucket("files/ffa/7ee/ffa7ee54-8c0f-465f-bf1f-f8cd1d4179e3/")`

**Comment by nitisht** [comment]
@looksworking `mc` is a tool that replicates `mkdir` behaviour and hence allows creating prefix within a bucket. `minio-java` is an SDK that is meant to be used by other applications.

Since a bucket and prefix are totally different, allowing prefixes created by `makeBucket` call is not helpful. This is why you see this difference, but this is by design.

**Comment by looksworking** [comment]
@nitisht ok, thanks for clarification. so if I need to create buckets with prefixes I will have to make several requests through the network before I can save my file to the correct bucket, or there is some way to minimize latency in this case?

**Comment by nitisht** [comment]
>  there is some way to minimize latency in this case?

You can try `putObject` with prefix added to the object name, that should work

**Comment by looksworking** [comment]
> You can try putObject with prefix added to the object name, that should work
It does, thanks again!
