### ISSUE TITLE
how to use composeObject

### ISSUE THREAD

**Issue by gitfortune** [minio/minio-java#892]
Hi,I have a problem with `composeObject`,in the Java Client API,version 7.0.1,not use aws s3.  I'm trying to upload some large video file via the `putObject`.Here's my plan,a video file will be slice from the frontend side.then frontend side receive slice data and use `putObject `API to upload. finally,use `composeObject` API to creates a complete video file by combining data.But it didn't work.I got a new video file,The video size is correct,but the content is wrong,it's only have the first part of video. Here is my test code，I upload there different video file named part1.mp4,part2.mp4,part3.mp4 and try to combining them.  is there any details I miss? any help or suggestions would be hugely appreciated,thank you very much!
![test](https://user-images.githubusercontent.com/8587865/78880972-bf30aa80-7a88-11ea-810b-ea64d0f7c0fa.png)
![test2](https://user-images.githubusercontent.com/8587865/78880989-c5268b80-7a88-11ea-83d3-2a70ebe72a79.png)

**Comment by gitfortune** [comment]
As shown in figure

**Comment by balamurugana** [comment]
`composeObject()` works something like unix `cat` command. Consider below example;
```bash
$ cat f1
hello
$ cat f2
world
$ cat f1 f2 > f-one-two
$ cat f-one-two
helloworld
```
If you do `composeObject()` with `mp4` files, it creates one single `mp4` file by having concatenated data. In an user point of view, it does not play video continuously because `mp4` video format does not allow. You would need to find how to transcode and combine videos for `mp4` video format.

However `composeObject()` works correctly for below case
* consider you have one single big `mp4` file and you split it into three parts
```bash
$ split -n 3 big.mp4
```
* Now you have three chunk files of `big.mp4` e.g. `xaa`, `xab` and `xac`. Upload those chunk files `xaa`, `xab` and `xac` using `putObject()`
* Then use `composeObject()` to combine those chunk files into `big.mp4`.  Now `big.mp4` is playable.

**Comment by gitfortune** [comment]
It worked,thank you!
